# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  imageRepo: sampleapp
  tag: '$(Build.BuildId)'
stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image      
      inputs:
        containerRegistry: 'aksregistry'
        repository: '$(imageRepo)'
        command: 'buildAndPush'      
        Dockerfile: '$(Build.SourcesDirectory)/app/Dockerfile'
        tags: |
          $(tag)
    - task: PublishPipelineArtifact@1
      inputs:
         targetPath: '$(Pipeline.Workspace)/s/kubernetes'
         artifact: 'manisfests'
         publishLocation: 'pipeline'
- stage: Deploy
  displayName: deploy to Dev
  dependsOn: Build
  variables:
      acrsecert:  
  jobs:
  - deployment: Deploy
    displayName: Deploy to AKS
    environment: 'k8sdev.monitoring'
    pool: 
      vmImage: ubuntu-latest
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadPipelineArtifact@2
            inputs:
              buildType: 'current'
              artifactName: 'manifests'
              targetPath: '$(Pipeline.Workspace)/manifests'            
          - task: DownloadPipelineArtifact@2
            inputs:
              buildType: 'current'
              artifactName: 'manifest'
              targetPath: '$(Pipeline.Workspace)/manifests'
          - task: KubernetesManifest@0
            inputs: 
              action: 'createSecret'
              kubernetesServiceConnection: 'akspr'
              namespace: 'monitoring'
              secretType: 'dockerRegistry'
              secretName: 'acrsecret'
              dockerRegistryEndpoint: 'aksregistry'
          - task: KubernetesManifest@0
            inputs:
              action: 'deploy'
              kubernetesServiceConnection: 'akspr'
              namespace: 'monitoring'
              manifests: 
                $(Pipeline.Workspace)/manifests/deployment.yml
                $(Pipeline.Workspace)/manifests/service.yml

